name: parayanken
favicon: null
layout_spectrum: 0.909492518287152
typography_spectrum: 0.2471330724656582
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.08470385591499507
  lightness: 0.8201248305849731
  saturation: 0.9692162305582315
  rhythmicContrast: 0.5621333448216319
purpose: []
